name: Test and Deploy Lambda Function

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: lambda_get_recipes

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r lambda_get_recipes/requirements.txt -t lambda_get_recipes/
          pip install pytest

      - name: Run unit tests
        run: |
          pytest lambda_get_recipes/tests/

  deploy:
    name: Deploy to Lambda
    runs-on: ubuntu-latest
    needs: test # <-- Ensures this job only runs if tests pass

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies for packaging
        run: |
          pip install -r lambda_get_recipes/requirements.txt -t lambda_get_recipes/

      - name: Zip get_recipes
        run: |
          cd lambda_get_recipes/app
          zip -r ../../get_recipes.zip .

      - name: Deploy get_recipes Lambda
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:044445073404:function:AllrecipesRecipeDataScraper \
            --zip-file fileb://get_recipes.zip \
            --handler app.lambda_function.lambda_handler
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
