name: Deploy Lambda Function

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # deploy lambda_get_links
      - name: Install dependencies for get_links
        run: |
          pip install -r lambda_get_links/requirements.txt -t lambda_get_links/
      - name: Zip get_links
        run: |
          cd lambda_get_links
          zip -r ../get_links.zip .
      - name: Deploy get_links Lambda
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:044445073404:function:AllrecipesRecipeLinkScraper \
            --zip-file fileb://get_links.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"

      # deploy lambda_get_recipes
      - name: Install dependencies for get_recipes
        run: |
          pip install -r lambda_get_recipes/requirements.txt -t lambda_get_recipes/
      - name: Zip get_recipes
        run: |
          cd lambda_get_recipes
          zip -r ../get_recipes.zip .
      - name: Deploy get_recipes Lambda
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:044445073404:function:AllrecipesRecipeDataScraper \
            --zip-file fileb://get_recipes.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
