name: Deploy Lambda Function

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # Install test dependencies
      - name: Install dependencies for get_recipes
        run: |
          pip install -r lambda_get_recipes/requirements.txt -t lambda_get_recipes/
          pip install pytest

      # Run unit tests for lambda_get_recipes
      - name: Run unit tests for get_recipes
        run: |
          # Set PYTHONPATH to lambda_get_recipes so tests can find the modules
          PYTHONPATH=lambda_get_recipes pytest lambda_get_recipes/tests/

      # Zip and deploy Lambda function
      - name: Zip get_recipes
        run: |
          cd lambda_get_recipes
          zip -r ../get_recipes.zip . -x "tests/*" "*.pyc" "__pycache__/*"

      - name: Deploy get_recipes Lambda
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:044445073404:function:AllrecipesRecipeDataScraper \
            --zip-file fileb://get_recipes.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
